version: '3'

services:
  db:
    image: postgres:12-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - spring-postgres

  backend:
    build: 
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - spring-postgres
networks:
  spring-postgres: